# itk-version: 3.2.3

services:
  phpfpm:
    image: itkdev/php8.4-fpm:latest
    user: ${COMPOSE_USER:-deploy}
    volumes:
      - .:/app

  markdownlint:
    image: itkdev/markdownlint
    profiles:
      - dev
    volumes:
      - ./:/md

  prettier:
    # Prettier does not (yet, fcf.
    # https://github.com/prettier/prettier/issues/15206) have an official
    # docker image.
    # https://hub.docker.com/r/jauderho/prettier is good candidate (cf. https://hub.docker.com/search?q=prettier&sort=updated_at&order=desc)
    image: jauderho/prettier
    profiles:
      - dev
    volumes:
      - ./:/work
