#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$script_dir"

execute() {
  composer require --dev symfony/phpunit-bridge
  # https://www.shellcheck.net/wiki/SC2154#exceptions
  shell vendor/bin/phpstan --configuration="${module_path:?}/phpstan.neon" --memory-limit=256M
}

# shellcheck source=/dev/null
source "$script_dir/base"
