#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$script_dir"

execute() {
  # https://www.shellcheck.net/wiki/SC2154#exceptions
  shell vendor/bin/rector --config="${module_path:?}/rector.php"
}

# shellcheck source=/dev/null
source "$script_dir/base"
